apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kuwp53c4i-go-gitops
  description: This is GitOps manifest for kuwp53c4i-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: kuwp53c4i-go
    janus-idp.io/tekton: kuwp53c4i-go
    backstage.io/kubernetes-id: kuwp53c4i-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:kuwp53c4i-go
